AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.mooveit::aws-lambda-spring-boot-container-poc
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  AwsLambdaSpringBootContainerPocFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.mooveit.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: target/aws-lambda-spring-boot-container-poc-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: test

Outputs:
  AwsLambdaSpringBootContainerPocApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: AwsLambdaSpringBootContainerPocApi
